//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.09 at 03:00:38 PM CEST 
//


package com.example.demo.xmlmodel;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.xmlmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ime_QNAME = new QName("", "ime");
    private final static QName _Prezime_QNAME = new QName("", "prezime");
    private final static QName _SifraPlacanja_QNAME = new QName("", "sifraPlacanja");
    private final static QName _Iznos_QNAME = new QName("", "iznos");
    private final static QName _RacunDuznika_QNAME = new QName("", "racunDuznika");
    private final static QName _DatumPrijema_QNAME = new QName("", "datumPrijema");
    private final static QName _PozivNaBrojOdobrenja_QNAME = new QName("", "pozivNaBrojOdobrenja");
    private final static QName _ModelZaduzenja_QNAME = new QName("", "modelZaduzenja");
    private final static QName _PozivNaBrojZaduzenja_QNAME = new QName("", "pozivNaBrojZaduzenja");
    private final static QName _ModelOdobrenja_QNAME = new QName("", "modelOdobrenja");
    private final static QName _DatumValute_QNAME = new QName("", "datumValute");
    private final static QName _SvrhaPlacanja_QNAME = new QName("", "svrhaPlacanja");
    private final static QName _Adresa_QNAME = new QName("", "adresa");
    private final static QName _RacunPoverioca_QNAME = new QName("", "racunPoverioca");
    private final static QName _Hitno_QNAME = new QName("", "hitno");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.xmlmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PodaciODuzniku }
     * 
     */
    public PodaciODuzniku createPodaciODuzniku() {
        return new PodaciODuzniku();
    }

    /**
     * Create an instance of {@link PodaciOPoveriocu }
     * 
     */
    public PodaciOPoveriocu createPodaciOPoveriocu() {
        return new PodaciOPoveriocu();
    }

    /**
     * Create an instance of {@link Uplatnica }
     * 
     */
    public Uplatnica createUplatnica() {
        return new Uplatnica();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIme(String value) {
        return new JAXBElement<String>(_Ime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prezime")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrezime(String value) {
        return new JAXBElement<String>(_Prezime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sifraPlacanja")
    public JAXBElement<BigInteger> createSifraPlacanja(BigInteger value) {
        return new JAXBElement<BigInteger>(_SifraPlacanja_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iznos")
    public JAXBElement<BigDecimal> createIznos(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Iznos_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "racunDuznika")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRacunDuznika(String value) {
        return new JAXBElement<String>(_RacunDuznika_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datumPrijema")
    public JAXBElement<XMLGregorianCalendar> createDatumPrijema(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumPrijema_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pozivNaBrojOdobrenja")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPozivNaBrojOdobrenja(String value) {
        return new JAXBElement<String>(_PozivNaBrojOdobrenja_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modelZaduzenja")
    public JAXBElement<BigInteger> createModelZaduzenja(BigInteger value) {
        return new JAXBElement<BigInteger>(_ModelZaduzenja_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pozivNaBrojZaduzenja")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPozivNaBrojZaduzenja(String value) {
        return new JAXBElement<String>(_PozivNaBrojZaduzenja_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modelOdobrenja")
    public JAXBElement<BigInteger> createModelOdobrenja(BigInteger value) {
        return new JAXBElement<BigInteger>(_ModelOdobrenja_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datumValute")
    public JAXBElement<XMLGregorianCalendar> createDatumValute(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumValute_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "svrhaPlacanja")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSvrhaPlacanja(String value) {
        return new JAXBElement<String>(_SvrhaPlacanja_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "adresa")
    public JAXBElement<String> createAdresa(String value) {
        return new JAXBElement<String>(_Adresa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "racunPoverioca")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRacunPoverioca(String value) {
        return new JAXBElement<String>(_RacunPoverioca_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hitno")
    public JAXBElement<Boolean> createHitno(Boolean value) {
        return new JAXBElement<Boolean>(_Hitno_QNAME, Boolean.class, null, value);
    }

}
